### ISSUE TITLE
If local data center nodes are down then it will get the data from other data center replica nodes?

### ISSUE THREAD

**Issue by raihan26** [Netflix/astyanax#321]
I have recently started using Cassandra in our Production environment. We have a 24 node cross colo cluster with replication factor of 4. We have 12 nodes in PHX and 12 nodes in SLC colo Becasue of replication factor 2 copies will be there in each datacenter.

I am using Astyanax client to read the data in Cassandra database. Below is the code I am using with Astyanax client that will auto discover all the nodes for each datacenter. Currently it will auto discover the nodes for PHX colo.

```
private CassandraAstyanaxConnection() {

    context = new AstyanaxContext.Builder()
    .forCluster(ModelConstants.CLUSTER)
    .forKeyspace(ModelConstants.KEYSPACE)
    .withConnectionPoolConfiguration(new ConnectionPoolConfigurationImpl("MyConnectionPool")
        .setPort(9160)
        .setMaxConnsPerHost(40)
        .setSeeds("cdb03.vip.phx.host.com:9160,cdb04.vip.phx.host.com:9160")
        .setLocalDatacenter("phx")
    )
    .withAstyanaxConfiguration(new AstyanaxConfigurationImpl()
        .setCqlVersion("3.0.0")
        .setTargetCassandraVersion("1.2")
        .setConnectionPoolType(ConnectionPoolType.TOKEN_AWARE))
    .withConnectionPoolMonitor(new CountingConnectionPoolMonitor())
    .buildKeyspace(ThriftFamilyFactory.getInstance());

    context.start();
    keyspace = context.getEntity();

    emp_cf = ColumnFamily.newColumnFamily(
        ModelConstants.COLUMN_FAMILY, 
        StringSerializer.get(), 
        StringSerializer.get());
}
```

Now I am trying to understand what will happen in these two scenarios-

1) We have a replication factor of 4 so that means 2 copies of same data will be there in each colo. Now with the current configuration of Astyanax that I am using currently (see above code) which will auto discover the nodes only for each datacenter right? Currently it is PHX. So suppose I am looking for rowKey 123 then it will go and get the data from two replicas in PHX colo, right?

2) What about this scenario- Then what will happen in that case, suppose two nodes in PHX that will contain the data for rowKey 123 are down? Then it will go and get the data from SLC colo replicas nodes? Am I correct?

**Comment by blakehawkins** [comment]
@opuneet , if you know, can you please tell me if functionality addressing the issue described above has been added in the 4 years since this was discussed?

In my case I'm using C* as a backup data store, and we intentionally expect entire "data centers" to fail.

Sadly, DNS is also not an option.

I suspect that we'll need to use two astyanax configurations open simultaneously, and try/except on them.

Please advise.
