### ISSUE TITLE
Note that Astyanax is being retired?

### ISSUE THREAD

**Issue by danielcompton** [Netflix/astyanax#632]
This [blog post](https://medium.com/netflix-techblog/astyanax-retiring-an-old-friend-6cca1de9ac4) says that Astyanax is being retired, but the README says:

> Astyanax is currently in use at Netflix. Issues generally are fixed as quickly as possible and releases done frequently.

which implies it is not being retired. It could be good to update the README to note this library being retired?

**Comment by arunagrawal84** [comment]
@danielcompton Astyanax is in sunset mode in Netflix i.e. any new use-case should NOT be using Astyanax but any existing projects using Astyanax can continue to do so. We believe that organic movement of applications (rewrite/refactor) should be sufficient in removing that dependency on Astyanax and applications adopting Cassandra java driver.  
We will patch Astyanax if we find some serious issue but there is no active development. But I agree on making the README to reflect the reality of being in "maintenance" mode.
